name: Setup
description: Setup
author: "danicc097@gmail.com"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2

    - uses: pnpm/action-setup@v2
      with:
        version: 7.6.0

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: "^1.19.1"

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - uses: actions/setup-node@v3
      with:
        node-version: 18

    - uses: pnpm/action-setup@v2
      with:
        version: 7.18.2
        run_install: false

    - name: Get pnpm store directory
      id: pnpm-cache
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies (1)
      shell: bash
      run: |
        source .envrc

        mv docker/.env.ci docker/.env

        { yes || :; } | project bootstrap --x-env=ci # https://stackoverflow.com/questions/49430554/gitlab-runner-in-docker-yes-true-returns-with-exit-1

        # project e2e.sync-deps --x-env=ci # won't use python playwright

    - name: Install dependencies (2)
      shell: bash
      run: |
        source .envrc

        git clone https://github.com/danicc097/traefik-bootstrap.git
        docker network create traefik-net || true
        cd traefik-bootstrap
        ./mkcert-certificates
        ./compose-up

        echo "$HOME/.local/bin" >> $GITHUB_PATH
        echo "$HOME/bin" >> $GITHUB_PATH
